apiVersion: apps/v1
kind: Deployment
metadata:
  name: nai-chatapp
  labels:
    app: nai-chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nai-chatapp
  template:
    metadata:
      labels:
        app: nai-chatapp
    spec:
      containers:
      - name: nai-chatapp
        image: johnugeorge/nai-chatapp:0.12
        ports:
        - containerPort: 8502
---
apiVersion: v1
kind: Service
metadata:
  name: nai-chatapp
spec:
  selector:
    app: nai-chatapp
  ports:
    - protocol: TCP
      port: 8502
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nai-chat
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - chat.cnai.irs-nai-nkp.cloudnative.nvdlab.net
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nai-chatapp
        port:
          number: 8502
